# ========== Configuration API Back Office ==========
# URL de base de l'API Back Office
api.base.url=http://localhost:8084

# Token d'authentification pour accéder aux API protégées
api.token=bc79cf5c-9b85-4374-8271-d9e95925d0cd
